name: Django Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-django-app .

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env

      - name: Run Docker container
        run: |
          docker run -d --name my-django-container \
            --env-file .env \
            -p 8000:8000 my-django-app

      - name: Wait for the container to be ready
        run: |
          echo "Waiting for the Django app to start..."
          sleep 10  # Adjust sleep time as needed

      - name: Run migrations
        run: |
          docker exec my-django-container python manage.py migrate

      - name: Run tests
        run: |
          docker exec my-django-container python manage.py test

      - name: Clean up
        if: always()
        run: |
          docker stop my-django-container || true
          docker rm my-django-container || true
