name: Django Test CI

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not "main"
  pull_request:
    branches:
      - main  # Change this to your default branch if it's not "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-django-app .

      - name: Create .env file from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" | base64 --decode > .env

      - name: Run Docker container
        run: |
          docker run -d --name my-django-container \
            --env-file .env \
            -p 8000:8000 my-django-app

      - name: Wait for the container to be ready
        run: |
          echo "Waiting for the Django app to start..."
          for i in {1..10}; do
            if curl -s http://localhost:8000/; then
              echo "Django app is running."
              break
            fi
            echo "Waiting..."
            sleep 5
          done
          
      - name: Run migrations
        run: |
          docker exec my-django-container python manage.py migrate

      - name: Run tests
        run: |
          docker exec my-django-container python manage.py test

      - name: Clean up
        if: always()
        run: |
          docker stop my-django-container || true
          docker rm my-django-container || true
